# Generated by Django 5.2.4 on 2025-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Branch', models.CharField(max_length=100)),
                ('Marks', models.IntegerField()),
            ],
        ),
    ]
